### ISSUE TITLE
Game Broker

### ISSUE THREAD

**Issue by john-winko** [john-winko/PoeAcolyte#7]
- [x] Handle events received by #1 
- [x] Set #1 active while game client is open / shut it off when game client is closed
- [x] Create #4 based on events from #5 
- [x] Manage custom state information such as when player enters hideout (#5)
